apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: show-ip
  namespace: show-ip
spec:
  minAvailable: 1  # Specifies the minimum number of pods that must be available
  selector:
    matchLabels:
      app.kubernetes.io/name: show-ip  # Replace with your app's label selector

